In [1]:
import numpy as np
import os

In [2]:
S0 = 83.43              # spot stock price (Has been calculated)
K = 70.0                # strike 
T = 1.0                 # maturity 
r = 0.92                # risk free rate (USA)
sig = 37.59             # volatility (Annualized)
N = 3                   # number of periods or number of time steps  
payoff = "put"          # payoff

In [3]:
dT = float(T) / N                             # Delta t
u = np.exp(sig * np.sqrt(dT))                 # up factor
d = 1.0 / u                                   # down factor

In [4]:
S = np.zeros((N + 1, N + 1))
S[0, 0] = S0
z = 1
for t in range(1, N + 1):
    for i in range(z):
        S[i, t] = S[i, t-1] * u
        S[i+1, t] = S[i, t-1] * d
    z += 1

In [5]:

S

array([[8.34300000e+01, 2.22146870e+11, 5.91504636e+20, 1.57498386e+30],
       [0.00000000e+00, 3.13331667e-08, 8.34300000e+01, 2.22146870e+11],
       [0.00000000e+00, 0.00000000e+00, 1.17675576e-17, 3.13331667e-08],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.41945158e-27]])

In [6]:
a = np.exp(r * dT)    # risk free compound return
p = (a - d)/ (u - d)  # risk neutral up probability
q = 1.0 - p           # risk neutral down probability
p

5.1034714134949e-10

In [7]:
S_T = S[:,-1]
V = np.zeros((N + 1, N + 1))
if payoff =="call":
    V[:,-1] = np.maximum(S_T-K, 0.0)
elif payoff =="put":
    V[:,-1] = np.maximum(K-S_T, 0.0)
V

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , 69.99999997],
       [ 0.        ,  0.        ,  0.        , 70.        ]])

In [8]:
# for American Option
if payoff =="call":
    for j in range(N-1, -1, -1):
        for i in range(j+1):
            V[i,j] = np.maximum(S[i,j] - K,np.exp(-r*dT) * (p * V[i,j + 1] + q * V[i + 1,j + 1]))
elif payoff =="put":
    for j in range(N-1, -1, -1):
        for i in range(j+1):
            V[i,j] = np.maximum(K - S[i,j],np.exp(-r*dT) * (p * V[i,j + 1] + q * V[i + 1,j + 1]))
V

array([[51.51271007, 37.90798998,  0.        ,  0.        ],
       [ 0.        , 69.99999997, 51.51271006,  0.        ],
       [ 0.        ,  0.        , 70.        , 69.99999997],
       [ 0.        ,  0.        ,  0.        , 70.        ]])

In [9]:
print('American ' + payoff, str( V[0,0]))

American put 51.512710070266415
